### PR TITLE
Write about the first Starterkit

### PR DESCRIPTION
**Pull request by kdungs**
Extensive mention of helpers and instructors (with picture) as well as
links to materials and mentions.

### CODE REVIEW

**Comment by apuignav** [comment]
I think we could also have a mention to the social/networking part of the event, something like (except for bad English):

"As part of the Starterkit goal of helping young colleagues to start out in the collaboration, a social/networking event was organized. It consisted in a barbecue that took place in the LHCb pit and in which both attendees, helpers and instructors could interact in a relaxed environment."

Whato do you think?

**Comment by betatim** [comment]
I'd just write "As part of the starterkit there was a social event: BBQ at the LHCb experiment." I'd leave out the "gives opportunity to mingle ..."

**Comment by betatim** [comment]
LGTM

**Comment by betatim** [comment]
.

**Pull request merged**
