### PR TITLE
Update November page with post-workshop summary

### PR DESCRIPTION
**Pull request by alexpearce**
It's over! 🎉 

The summary is a little cheesy, but what the heck, it was fun 😄

### CODE REVIEW

**Comment by chrisburr** [comment]
It needs rebasing but other than that it looks great to me! 🧀

**Comment by apuignav** [comment]
Beautiful! Once conflicts are solved, LGTM!

**Comment by ibab** [comment]
@alexpearce has smashed it again 🍞

**Comment by cmarinbe** [comment]
I don't know how it works but we also need to move it under "Previous workshops", it's over! 🎂

**Comment by saschastahl** [comment]
In line 113 it should be Svende not Svenda.

**Comment by alexpearce** [comment]
Thanks @saschastahl, fixed.

Rebased now, should be good to go.

**Comment by ibab** [comment]
Thank you, @alexpearce! :tada:

**Pull request merged**
